// frontend/src/lib/components/landing/Header.svelte
<script lang="ts">
	import { theme } from '$lib/theme.svelte';
	import { auth } from '$lib/auth.svelte';
	import { resolve } from '$app/paths';
	import { track } from '$lib/analytics';
	import { onMount } from 'svelte';
	import Logo from '$lib/components/Logo.svelte';

	let mobileOpen = $state(false);
	let scrolled = $state(false);

	onMount(() => {
		const onScroll = () => {
			scrolled = window.scrollY > 8;
		};
		onScroll();
		window.addEventListener('scroll', onScroll, { passive: true });
		return () => window.removeEventListener('scroll', onScroll);
	});

	$effect(() => {
		if (typeof document !== 'undefined') {
			document.body.style.overflow = mobileOpen ? 'hidden' : '';
		}
	});

	function closeMenu() {
		mobileOpen = false;
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') closeMenu();
	}
</script>

<header
	aria-label="Primary"
	class="sticky top-0 z-30 border-b border-border/70 bg-(--color-bg)/85 backdrop-blur {scrolled
		? 'shadow-sm'
		: ''}"
>
	<div class="mx-auto flex max-w-6xl items-center justify-between gap-6 px-6 py-4">
		<a href={resolve('/')} aria-label="elci home" class="shrink-0 text-(--color-logo)">
			<Logo />
		</a>
		<nav aria-label="Primary" class="hidden items-center gap-8 text-sm font-medium text-(--color-text-muted) md:flex">
			<ul class="flex items-center gap-8">
				<li><a href="#product" class="hover:text-(--color-text)">Product</a></li>
				<li><a href="#how-it-works" class="hover:text-(--color-text)">How it works</a></li>
				<li><a href="#faq" class="hover:text-(--color-text)">FAQ</a></li>
			</ul>
		</nav>

		<div class="flex items-center gap-3">
			<button
				type="button"
				onclick={() => theme.toggle()}
				aria-label="Toggle color theme"
				aria-pressed={theme.current === 'dark'}
				class="grid h-9 w-9 place-items-center rounded-full border border-border text-(--color-text-muted) transition hover:text-(--color-text)"
			>
				{#if theme.current === 'dark'}
					<svg
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="1.7"
						class="h-4 w-4"
						aria-hidden="true"
						focusable="false"
					>
						<circle cx="12" cy="12" r="4.5" />
						<path
							d="M12 2.5v2M12 19.5v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M2.5 12h2M19.5 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4"
							stroke-linecap="round"
						/>
					</svg>
				{:else}
					<svg
						viewBox="0 0 24 24"
						fill="currentColor"
						class="h-4 w-4"
						aria-hidden="true"
						focusable="false"
					>
						<path d="M20 14.5A8.5 8.5 0 0 1 9.5 4a8.5 8.5 0 1 0 10.5 10.5Z" />
					</svg>
				{/if}
			</button>
			<a
				href={auth.isAuthenticated ? resolve('/dashboard') : resolve('/login')}
				data-analytics="header-cta"
				onclick={() => track('header-cta')}
				class="rounded-full bg-(--color-navy) px-4 py-2 text-sm font-semibold text-white transition hover:opacity-90"
			>
				{auth.isAuthenticated ? 'Dashboard' : 'Get started'}
			</a>
			<button
				type="button"
				class="grid h-9 w-9 place-items-center rounded-full border border-border text-(--color-text-muted) md:hidden"
				aria-label="Open navigation menu"
				aria-expanded={mobileOpen}
				aria-controls="mobile-nav"
				onclick={() => (mobileOpen = !mobileOpen)}
			>
				<svg
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="1.8"
					class="h-5 w-5"
					aria-hidden="true"
					focusable="false"
				>
					{#if mobileOpen}
						<path d="M6 6 18 18M18 6 6 18" stroke-linecap="round" />
					{:else}
						<path d="M4 7h16M4 12h16M4 17h16" stroke-linecap="round" />
					{/if}
				</svg>
			</button>
		</div>
	</div>

	{#if mobileOpen}
		<!-- svelte-ignore a11y_interactive_supports_focus -->
		<div
			id="mobile-nav"
			role="dialog"
			aria-modal="true"
			aria-label="Navigation menu"
			tabindex="-1"
			class="fixed inset-0 z-40 flex flex-col bg-(--color-bg) px-6 pt-20 pb-8 md:hidden"
			onkeydown={handleKeydown}
		>
			<button
				type="button"
				aria-label="Close navigation menu"
				class="absolute top-4 right-6 grid h-9 w-9 place-items-center rounded-full border border-border"
				onclick={closeMenu}
			>
				<svg
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="1.8"
					class="h-5 w-5"
					aria-hidden="true"
					focusable="false"
				>
					<path d="M6 6 18 18M18 6 6 18" stroke-linecap="round" />
				</svg>
			</button>
			<nav aria-label="Mobile" class="flex flex-col gap-6 text-lg font-medium">
				<!-- svelte-ignore a11y_autofocus -->
				<a href="#product" onclick={closeMenu} autofocus class="hover:text-(--color-text)"
					>Product</a
				>
				<a href="#how-it-works" onclick={closeMenu} class="hover:text-(--color-text)"
					>How it works</a
				>
				<a href="#faq" onclick={closeMenu} class="hover:text-(--color-text)">FAQ</a>
				<a
					href={auth.isAuthenticated ? resolve('/dashboard') : resolve('/login')}
					onclick={() => {
						track('header-cta');
						closeMenu();
					}}
					data-analytics="header-cta"
					class="mt-4 inline-block rounded-full bg-(--color-navy) px-6 py-3 text-center text-sm font-semibold text-white"
				>
					{auth.isAuthenticated ? 'Dashboard' : 'Get started'}</a
				>
			</nav>
		</div>
	{/if}
</header>

// frontend/src/components/landing/Header.tsx
import { Link } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { useState } from 'react'

export function Header() {
  const { isAuthenticated, loginTikTok, loginX, loginInstagram } = useAuth()
  const [showAuthModal, setShowAuthModal] = useState(false)

  const handleGetStarted = () => {
    setShowAuthModal(true)
  }

  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-br from-indigo-600 to-purple-600 rounded-lg flex items-center justify-center">
              <svg className="w-5 h-5 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M12 2L2 7l10 5 10-5-10-5z" />
                <path d="M2 17l10 5 10-5" />
                <path d="M2 12l10 5 10-5" />
              </svg>
            </div>
            <span className="font-semibold text-gray-900">elci.io</span>
          </Link>

          <nav className="hidden md:flex items-center gap-8">
            <a href="#how-it-works" className="text-gray-600 hover:text-gray-900 transition-colors">
              How It Works
            </a>
            <a href="#benefits" className="text-gray-600 hover:text-gray-900 transition-colors">
              Benefits
            </a>
            <Link to="/privacy-policy" className="text-gray-600 hover:text-gray-900 transition-colors">
              Privacy
            </Link>
          </nav>

          <div className="flex items-center gap-4">
            {isAuthenticated ? (
              <Link
                to="/dashboard"
                className="px-5 py-2.5 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-lg hover:shadow-lg hover:scale-105 transition-all"
              >
                Go to Dashboard
              </Link>
            ) : (
              <>
                <button
                  onClick={handleGetStarted}
                  className="hidden sm:block text-gray-600 hover:text-gray-900 transition-colors"
                >
                  Sign In
                </button>
                <button
                  onClick={handleGetStarted}
                  className="px-5 py-2.5 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-lg hover:shadow-lg hover:scale-105 transition-all"
                >
                  Get Started
                </button>
              </>
            )}
          </div>
        </div>
      </header>

      {/* Auth Modal */}
      {showAuthModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm" onClick={() => setShowAuthModal(false)}>
          <div className="bg-white rounded-2xl p-8 max-w-md w-full mx-4 shadow-2xl" onClick={(e) => e.stopPropagation()}>
            <div className="text-center mb-6">
              <h2 className="text-2xl font-bold text-gray-900 mb-2">Choose a platform to continue</h2>
              <p className="text-gray-600">Connect with your favorite platform to get started</p>
            </div>

            <div className="space-y-3">
              <button
                onClick={loginTikTok}
                className="w-full flex items-center justify-center gap-3 px-6 py-4 bg-black text-white rounded-lg hover:bg-gray-800 transition-all font-medium"
              >
                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M19.59 6.69a4.83 4.83 0 0 1-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 0 1-5.2 1.74 2.89 2.89 0 0 1 2.31-4.64 2.93 2.93 0 0 1 .88.13V9.4a6.84 6.84 0 0 0-1-.05A6.33 6.33 0 0 0 5 20.1a6.34 6.34 0 0 0 10.86-4.43v-7a8.16 8.16 0 0 0 4.77 1.52v-3.4a4.85 4.85 0 0 1-1-.1z" />
                </svg>
                Continue with TikTok
              </button>

              <button
                onClick={loginX}
                className="w-full flex items-center justify-center gap-3 px-6 py-4 bg-black text-white rounded-lg hover:bg-gray-800 transition-all font-medium"
              >
                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                </svg>
                Continue with X
              </button>

              <button
                onClick={loginInstagram}
                className="w-full flex items-center justify-center gap-3 px-6 py-4 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg hover:from-purple-700 hover:to-pink-700 transition-all font-medium"
              >
                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z" />
                </svg>
                Continue with Instagram
              </button>
            </div>

            <button
              onClick={() => setShowAuthModal(false)}
              className="mt-6 w-full px-6 py-3 text-gray-600 hover:text-gray-900 transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </>
  )
}
