// frontend/src/lib/components/landing-v2/Header.svelte
<script lang="ts">
	import { theme } from '$lib/theme.svelte';
	import { auth } from '$lib/auth.svelte';
	import { resolve } from '$app/paths';

	let menuOpen = $state(false);

	const links = [
		{ href: '#product', label: 'Product' },
		{ href: '#how-it-works', label: 'How it works' },
		{ href: '#agents', label: 'For agents' },
		{ href: '#faq', label: 'FAQ' }
	];

	function closeMenu() {
		menuOpen = false;
	}
</script>

<div class="pointer-events-none fixed inset-x-0 top-0 z-40 mt-6 flex justify-center px-4">
	<header
		class="pointer-events-auto w-max max-w-[calc(100vw-2rem)] rounded-full border border-border bg-(--color-surface)/80 shadow-[0_8px_30px_-15px_rgba(16,24,40,0.25)] backdrop-blur-xl transition-all duration-700 ease-[cubic-bezier(0.32,0.72,0,1)]"
	>
		<div class="flex items-center gap-6 px-4 py-2.5 md:gap-8 md:px-5">
			<a href={resolve('/')} class="flex items-center gap-2 text-base font-semibold">
				elci
				<span class="inline-block h-1.5 w-1.5 rounded-full bg-(--color-accent)"></span>
			</a>

			<nav class="hidden items-center gap-6 text-sm font-medium text-(--color-text-muted) md:flex">
				{#each links as link (link.href)}
					<a href={link.href} class="pill-nav-link hover:text-(--color-text)">{link.label}</a>
				{/each}
			</nav>

			<div class="hidden items-center gap-3 md:flex">
				<button
					type="button"
					onclick={() => theme.toggle()}
					aria-label="Toggle color theme"
					class="grid h-8 w-8 place-items-center rounded-full border border-border text-(--color-text-muted) transition hover:text-(--color-text)"
				>
					{#if theme.current === 'dark'}
						<svg
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="1.7"
							class="h-4 w-4"
						>
							<circle cx="12" cy="12" r="4.5" />
							<path
								d="M12 2.5v2M12 19.5v2M4.2 4.2l1.4 1.4M18.4 18.4l1.4 1.4M2.5 12h2M19.5 12h2M4.2 19.8l1.4-1.4M18.4 5.6l1.4-1.4"
								stroke-linecap="round"
							/>
						</svg>
					{:else}
						<svg viewBox="0 0 24 24" fill="currentColor" class="h-4 w-4">
							<path d="M20 14.5A8.5 8.5 0 0 1 9.5 4a8.5 8.5 0 1 0 10.5 10.5Z" />
						</svg>
					{/if}
				</button>
				<a
					href={auth.isAuthenticated ? resolve('/dashboard') : resolve('/login')}
					class="rounded-full bg-(--color-navy) px-4 py-2 text-sm font-semibold text-white transition hover:opacity-90"
				>
					{auth.isAuthenticated ? 'Dashboard' : 'Get started'}
				</a>
			</div>

			<button
				type="button"
				class="relative grid h-8 w-8 place-items-center md:hidden"
				aria-label={menuOpen ? 'Close menu' : 'Open menu'}
				aria-expanded={menuOpen}
				onclick={() => (menuOpen = !menuOpen)}
			>
				<span
					class="hamburger-line absolute h-[1.5px] w-4 bg-(--color-text)"
					style={menuOpen
						? 'transform: translateY(0) rotate(45deg)'
						: 'transform: translateY(-4px)'}
				></span>
				<span
					class="hamburger-line absolute h-[1.5px] w-4 bg-(--color-text)"
					style={menuOpen
						? 'transform: translateY(0) rotate(-45deg)'
						: 'transform: translateY(4px)'}
				></span>
			</button>
		</div>
	</header>
</div>

<div
	class="fixed inset-0 z-30 bg-(--color-bg)/95 backdrop-blur-3xl transition-opacity duration-700 ease-[cubic-bezier(0.32,0.72,0,1)] md:hidden {menuOpen
		? 'pointer-events-auto opacity-100'
		: 'pointer-events-none opacity-0'}"
	aria-hidden={!menuOpen}
>
	<nav
		class="flex h-full flex-col items-center justify-center gap-8 text-2xl font-medium {menuOpen
			? 'nav-open'
			: ''}"
	>
		{#each links as link, i (link.href)}
			<a
				href={link.href}
				class="nav-word"
				style="transition-delay: {100 + i * 50}ms"
				onclick={closeMenu}
				tabindex={menuOpen ? 0 : -1}
			>
				{link.label}
			</a>
		{/each}
		<a
			href={auth.isAuthenticated ? resolve('/dashboard') : resolve('/login')}
			class="nav-word mt-4 rounded-full bg-(--color-accent) px-6 py-3 text-base font-semibold text-white"
			style="transition-delay: {100 + links.length * 50}ms"
			onclick={closeMenu}
			tabindex={menuOpen ? 0 : -1}
		>
			{auth.isAuthenticated ? 'Dashboard' : 'Connect your accounts'}
		</a>
	</nav>
</div>

// frontend/src/components/landing/Header.tsx
import { Link } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { useState } from 'react'

export function Header() {
  const { isAuthenticated, loginTikTok, loginX, loginInstagram } = useAuth()
  const [showAuthModal, setShowAuthModal] = useState(false)

  const handleGetStarted = () => {
    setShowAuthModal(true)
  }

  return (
    <>
      <header className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-br from-indigo-600 to-purple-600 rounded-lg flex items-center justify-center">
              <svg className="w-5 h-5 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M12 2L2 7l10 5 10-5-10-5z" />
                <path d="M2 17l10 5 10-5" />
                <path d="M2 12l10 5 10-5" />
              </svg>
            </div>
            <span className="font-semibold text-gray-900">elci.io</span>
          </Link>

          <nav className="hidden md:flex items-center gap-8">
            <a href="#how-it-works" className="text-gray-600 hover:text-gray-900 transition-colors">
              How It Works
            </a>
            <a href="#benefits" className="text-gray-600 hover:text-gray-900 transition-colors">
              Benefits
            </a>
            <Link to="/privacy-policy" className="text-gray-600 hover:text-gray-900 transition-colors">
              Privacy
            </Link>
          </nav>

          <div className="flex items-center gap-4">
            {isAuthenticated ? (
              <Link
                to="/dashboard"
                className="px-5 py-2.5 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-lg hover:shadow-lg hover:scale-105 transition-all"
              >
                Go to Dashboard
              </Link>
            ) : (
              <>
                <button
                  onClick={handleGetStarted}
                  className="hidden sm:block text-gray-600 hover:text-gray-900 transition-colors"
                >
                  Sign In
                </button>
                <button
                  onClick={handleGetStarted}
                  className="px-5 py-2.5 bg-gradient-to-r from-indigo-600 to-purple-600 text-white rounded-lg hover:shadow-lg hover:scale-105 transition-all"
                >
                  Get Started
                </button>
              </>
            )}
          </div>
        </div>
      </header>

      {/* Auth Modal */}
      {showAuthModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm" onClick={() => setShowAuthModal(false)}>
          <div className="bg-white rounded-2xl p-8 max-w-md w-full mx-4 shadow-2xl" onClick={(e) => e.stopPropagation()}>
            <div className="text-center mb-6">
              <h2 className="text-2xl font-bold text-gray-900 mb-2">Choose a platform to continue</h2>
              <p className="text-gray-600">Connect with your favorite platform to get started</p>
            </div>

            <div className="space-y-3">
              <button
                onClick={loginTikTok}
                className="w-full flex items-center justify-center gap-3 px-6 py-4 bg-black text-white rounded-lg hover:bg-gray-800 transition-all font-medium"
              >
                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M19.59 6.69a4.83 4.83 0 0 1-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 0 1-5.2 1.74 2.89 2.89 0 0 1 2.31-4.64 2.93 2.93 0 0 1 .88.13V9.4a6.84 6.84 0 0 0-1-.05A6.33 6.33 0 0 0 5 20.1a6.34 6.34 0 0 0 10.86-4.43v-7a8.16 8.16 0 0 0 4.77 1.52v-3.4a4.85 4.85 0 0 1-1-.1z" />
                </svg>
                Continue with TikTok
              </button>

              <button
                onClick={loginX}
                className="w-full flex items-center justify-center gap-3 px-6 py-4 bg-black text-white rounded-lg hover:bg-gray-800 transition-all font-medium"
              >
                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
                </svg>
                Continue with X
              </button>

              <button
                onClick={loginInstagram}
                className="w-full flex items-center justify-center gap-3 px-6 py-4 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg hover:from-purple-700 hover:to-pink-700 transition-all font-medium"
              >
                <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z" />
                </svg>
                Continue with Instagram
              </button>
            </div>

            <button
              onClick={() => setShowAuthModal(false)}
              className="mt-6 w-full px-6 py-3 text-gray-600 hover:text-gray-900 transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      )}
    </>
  )
}
